"""empty message

Revision ID: 4653a2d39d90
Revises: a5cffa318ac2
Create Date: 2025-12-01 21:43:59.846573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4653a2d39d90'
down_revision = 'a5cffa318ac2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mass', sa.Integer(), nullable=False),
    sa.Column('hair_color', sa.String(length=100), nullable=False),
    sa.Column('skin_color', sa.String(length=100), nullable=False),
    sa.Column('eye_color', sa.String(length=100), nullable=False),
    sa.Column('birth_year', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('rotation_period', sa.Integer(), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(), nullable=False),
    sa.Column('gravity', sa.String(), nullable=False),
    sa.Column('terrain', sa.String(), nullable=False),
    sa.Column('surface_water', sa.String(), nullable=False),
    sa.Column('population', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav_characters',
    sa.Column('fav_user_id', sa.Integer(), nullable=True),
    sa.Column('fav_character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fav_character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['fav_user_id'], ['user.id'], )
    )
    op.create_table('fav_planets',
    sa.Column('fav_user_id', sa.Integer(), nullable=True),
    sa.Column('fav_planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['fav_planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['fav_user_id'], ['user.id'], )
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    op.drop_table('fav_planets')
    op.drop_table('fav_characters')
    op.drop_table('planet')
    op.drop_table('character')
    # ### end Alembic commands ###
